use lectionary_db;

INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (1, 'Almighty God, give us grace to cast away the works of darkness, and put on the armor of light, now in the time of this mortal life in which your Son Jesus Christ came to visit us in great humility; that in the last day, when he shall come again in his glorious majesty to judge both the living and the dead, we may rise to the life immortal; through him who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen', 'The First Sunday in Advent', null, 1);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (2, 'Blessed Lord, who caused all holy Scriptures to be written for our learning: Grant us so to hear them, read, mark, learn, and inwardly digest them, that by patience and the comfort of your Holy Word we may embrace and ever hold fast the blessed hope of everlasting life, which you have given us in our Savior Jesus Christ; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'The Second Sunday in Advent', null, 1);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (3, 'Lord Jesus Christ, who sent your messengers the prophets to preach repentance and prepare the way for our salvation: Grant that the ministers and stewards of your mysteries may likewise make ready your way, by turning the hearts of the disobedient to the wisdom of the just, that at your second coming to judge the world, we may be found a people acceptable in your sight; who with the Father and the Holy Spirit, lives and reigns, one God, now and forever. Amen. ', 'The Third Sunday in Advent', null, 1);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (4, 'Stir up your power, O Lord, and with great might come among us; and as we are sorely hindered by our sins from running the race that is set before us, let your bountiful grace and mercy speedily help and deliver us; through Jesus Christ our Lord, to whom, with you and the Holy Spirit, be honor and glory, now and forever. Amen ', 'The Fourth Sunday in Advent [Annunciation]', null, 1);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (5, 'O God, you have caused this holy night to shine with the brightness of the true Light: Grant that we, who have known the revelation of that Light on earth, may also enjoy him perfectly in heaven; where with you and the Holy Spirit he lives and reigns, one God, in glory everlasting. Amen. ', 'Christmas Eve', null, 2);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (6, 'Almighty God, you have given your only-begotten Son to take our nature upon him, and to be born [this day] of a pure virgin: Grant that we, who have been born again and made your children by adoption and grace, may daily be renewed by your Holy Spirit; through our Lord Jesus Christ, to whom with you and the same Spirit be honor and glory, now and forever.', 'Christmas Day', null, 2);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (7, 'Almighty God, you have poured upon us the new light of your incarnate Word: Grant that this light, enkindled in our hearts, may shine forth in our lives; through Jesus Christ our Lord; who lives and reigns with you, in the unity of the Holy Spirit, one God, now and forever. Amen. ', 'First Sunday of Christmas', null, 2);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (8, 'Almighty God, whose blessed Son was circumcised for our sake in obedience to the Covenant of Abraham, and given the Name that is above every name: give us the grace to faithfully bear his Name, to worship him in the Spirit given in the New Covenant, and to proclaim him as the Savior of the world; who lives and reigns with you, in the unity of the Holy Spirit, one God, now and forever. Amen. ', 'The Holy Name of Our Lord Jesus Christ', null, 2);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (9, 'O God, who wonderfully created, and yet more wonderfully restored, the dignity of human nature: Grant that we may share the divine life of him who humbled himself to share our humanity, your Son Jesus Christ; who lives and reigns with you, in the unity of the Holy Spirit, one God, for ever and ever. Amen. ', 'The Second Sunday of Christmas', null, 2);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (10, 'O God, by the leading of a star you manifested your only Son to the peoples of the earth: Lead us, who know you now by faith, to your presence, where we may see your glory face to face; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen. ', 'Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (11, 'Eternal Father, who at the baptism of Jesus revealed him to be your Son, anointing him with the Holy Spirit: grant to us, who are born again by water and the Spirit, that we may be faithful to our calling as your adopted children; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen.  ', 'The First Sunday of Epiphany [Baptism of Our Lord]', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (12, 'Almighty God, whose Son our Savior Jesus Christ is the light of the world: Grant that your people, illumined by your Word and Sacraments, may shine with the radiance of Christ’s glory, that he may be known, worshiped, and obeyed to the ends of the earth; through Jesus Christ our Lord; who with you and the Holy Spirit lives and reigns, one God, now and forever. Amen. ', 'The Second Sunday of Epiphany', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (13, 'Give us grace, O Lord, to answer readily the call of our Savior Jesus Christ and proclaim to all people the Good News of his salvation, that we and the whole world may perceive the glory of his marvelous works; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'The Third Sunday of Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (14, 'O God, you know that we are set in the midst of so many and grave dangers that in the frailty of our nature we cannot always stand upright: Grant us your strength and protection to support us in all dangers and carry us through every temptation; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, world without end. Amen.', 'The Fourth Sunday of Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (15, 'Almighty and everliving God, we humbly pray that, as your only-begotten Son was this day presented in the temple in the substance of our flesh, so we may be presented to you with pure and clean hearts by Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen. ', 'The Presentation of Christ in the Temple', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (16, 'O Lord, our Creator and Redeemer, we ask you to keep your household the Church continually in your true religion; so that we who trust in the hope of your heavenly grace may always be defended by your mighty power; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, both now and forever. Amen', 'The Fifth Sunday of Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (17, 'Almighty God, we ask you mercifully to look upon your people; that by your great goodness they may be governed and preserved evermore; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, now and forever. Amen.', 'The Sixth Sunday of Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (18, 'O God, the strength of all who put their trust in you: mercifully accept our prayers, and because through the weakness of our mortal nature we can do no good thing without you, grant us the help of your grace to keep your commandments; so that we may please you in will and deed; we ask this through Jesus Christ our Lord who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'The Seventh Sunday of Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (19, 'Lord God, you know that without your grace we cannot put our trust in anything that we do; defend us, by your mighty power, from all adversities which might assault and hurt our souls; we ask this through Jesus Christ our Lord; who with you and the Holy Spirit, lives and reigns as one God, now and forever. Amen. ', 'The Eighth Sunday of Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (20, 'Give us grace, O Lord, to answer readily the call of our Savior Jesus Christ and proclaim to all people the Good News of his salvation, that we and the whole world may perceive the glory of his marvelous works; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'The Second to last Sunday of Epiphany [World Mission Sunday]', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (21, 'O God, who before the passion of your only-begotten Son revealed his glory upon the holy mountain: Grant that we, beholding by faith the light of his countenance, may be strengthened to bear our cross, and be changed into his likeness from glory to glory; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'The Last Sunday of Epiphany  [Transfiguration]', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (22, 'Almighty and everlasting God, you hate nothing you have made and forgive the sins of all who are penitent: Create and make in us new and contrite hearts, that we, worthily lamenting our sins and acknowledging our wretchedness, may obtain of you, the God of all mercy, perfect remission and forgiveness; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'Ash Wednesday', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (23, 'Almighty God, whose blessed Son was led by the Spirit to be tempted by Satan: Come quickly to help us who are assaulted by many temptations; and, as you know the weaknesses of each of us, let each one find you mighty to save; through Jesus Christ your Son our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen. ', 'The First Sunday in Lent', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (24, 'Almighty God, you know that we have no power in ourselves to help ourselves: Keep us both outwardly in our bodies and inwardly in our souls, that we may be defended from all adversities which may happen to the body, and from all evil thoughts which may assault and hurt the soul; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen', 'The Second Sunday in Lent', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (25, 'Heavenly Father, you made us for yourself, and our hearts are restless until they rest in you: Look upon the heartfelt desires of your humble servants, and stretch forth the strong hand of your Majesty to be our defense against our enemies; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, world without end. Amen.', 'The Third Sunday in Lent
', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (26, 'Gracious Father, whose blessed Son Jesus Christ came down from heaven to be the true bread which gives life to the world: Evermore give us this bread, that he may live in us, and we in him; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen. ', 'The Fourth Sunday in Lent', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (27, 'Almighty God, you alone can bring into order the unruly wills and affections of sinners: Grant your people grace to love what you command and desire what you promise; that, among the swift and varied changes of this world, our hearts may surely there be fixed where true joys are to be found; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen. ', 'The Fifth Sunday in Lent [Passion Sunday]', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (28, 'Almighty and everliving God, in your tender love for the human race you sent your Son our Savior Jesus Christ to take upon himself our nature, and to suffer death upon the cross, giving us the example of his great humility: Mercifully grant that we may walk in the way of his suffering, and also share in his resurrection; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Palm Sunday', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (29, 'Almighty God, whose most dear Son went not up to joy but first he suffered pain, and entered not into glory before he was crucified: Mercifully grant that we, walking in the way of the cross, may find it none other than the way of life and peace; through Jesus Christ your Son our Lord [who lives and reigns with you and the Holy Spirit, one God, for ever and ever]. Amen', 'Monday of Holy Week', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (30, 'Lord our God, whose blessed Son our Savior gave his back to be whipped and did not hide his face from shame and spitting: Give us grace to accept joyfully the sufferings of the present time, confident of the glory that shall be revealed; through Jesus Christ your Son our Lord [who lives and reigns with you and the Holy Spirit, one God, for ever and ever]. Amen.', 'Tuesday of Holy Week', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (31, 'Assist us mercifully with your grace, Lord God of our salvation; that we may enter with joy upon the meditation of those mighty acts by which you have promised us life and immortality; through Jesus Christ our Lord [who lives and reigns with you and the Holy Spirit, one God, for ever and ever]. Amen.', 'Wednesday of Holy Week', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (32, 'Almighty Father, whose dear Son, on the night before he suffered, instituted the Sacrament of his Body and Blood: Mercifully grant that we may receive it thankfully in remembrance of Jesus Christ our Lord, who in these holy mysteries gives us a pledge of eternal life; [and who lives and reigns with you and the Holy Spirit, one God, for ever and ever]. Amen. ', 'Maundy Thursday', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (33, 'Almighty God, we pray you graciously to behold this your family, for whom our Lord Jesus Christ was willing to be betrayed, and given into the hands of sinners, and to suffer death upon the cross; [who now lives and reigns with you and the Holy Spirit, one God, for ever and ever]. Amen.', 'Good Friday', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (34, 'O God, Creator of heaven and earth: Grant that, as the crucified body of your dear Son was laid in the tomb and rested on this holy Sabbath, so we may await with him the coming of the third day, and rise with him to newness of life; through Jesus Christ our Lord. Amen.
or
O God of the living, on this day your Son descended to the place of the dead: Look with kindness on all of us who wait in hope for liberation from the corruption of sin and death, and give us a share in the glory of the children of God, through Jesus Christ your Son, our Lord. Amen.

and

O God, who made this most holy night to shine with the glory of the Lord’s resurrection: Stir up that Spirit of adoption which is given to your Church in Baptism, that we, being renewed both in body and mind, may worship you in sincerity and truth; through Jesus Christ our Lord, who lives and reigns with you, in the unity of the Holy Spirit, one God, now and forever. Amen.

', 'Holy Saturday and Easter Eve ', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (35, 'Almighty God, who through your only-begotten Son Jesus Christ overcame death and opened to us the gate of everlasting life: Grant that we, who celebrate with joy the day of the Lord’s resurrection, may be raised from the death of sin by your life-giving Spirit; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen

or

O God, who for our redemption gave your only begotten Son to die upon the cross, and by his glorious resurrection delivered us from the power of death and the devil: Grant us the grace to die daily to sin, that we may live with him in the joy of his resurrection, through the same, Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit now and forever. Amen', 'Easter Day', null, 5);