use lectionary_db;
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (1, 'Almighty God, give us grace to cast away the works of darkness, and put on the armor of light, now in the time of this mortal life in which your Son Jesus Christ came to visit us in great humility; that in the last day, when he shall come again in his glorious majesty to judge both the living and the dead, we may rise to the life immortal; through him who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen', 'The First Sunday in Advent', null, 1);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (2, 'Blessed Lord, who caused all holy Scriptures to be written for our learning: Grant us so to hear them, read, mark, learn, and inwardly digest them, that by patience and the comfort of your Holy Word we may embrace and ever hold fast the blessed hope of everlasting life, which you have given us in our Savior Jesus Christ; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'The Second Sunday in Advent', null, 1);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (3, 'Lord Jesus Christ, who sent your messengers the prophets to preach repentance and prepare the way for our salvation: Grant that the ministers and stewards of your mysteries may likewise make ready your way, by turning the hearts of the disobedient to the wisdom of the just, that at your second coming to judge the world, we may be found a people acceptable in your sight; who with the Father and the Holy Spirit, lives and reigns, one God, now and forever. Amen. ', 'The Third Sunday in Advent', null, 1);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (4, 'Stir up your power, O Lord, and with great might come among us; and as we are sorely hindered by our sins from running the race that is set before us, let your bountiful grace and mercy speedily help and deliver us; through Jesus Christ our Lord, to whom, with you and the Holy Spirit, be honor and glory, now and forever. Amen ', 'The Fourth Sunday in Advent [Annunciation]', null, 1);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (5, 'O God, you have caused this holy night to shine with the brightness of the true Light: Grant that we, who have known the revelation of that Light on earth, may also enjoy him perfectly in heaven; where with you and the Holy Spirit he lives and reigns, one God, in glory everlasting. Amen. ', 'Christmas Eve', null, 2);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (6, 'Almighty God, you have given your only-begotten Son to take our nature upon him, and to be born [this day] of a pure virgin: Grant that we, who have been born again and made your children by adoption and grace, may daily be renewed by your Holy Spirit; through our Lord Jesus Christ, to whom with you and the same Spirit be honor and glory, now and forever.', 'Christmas Day', null, 2);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (7, 'Almighty God, you have poured upon us the new light of your incarnate Word: Grant that this light, enkindled in our hearts, may shine forth in our lives; through Jesus Christ our Lord; who lives and reigns with you, in the unity of the Holy Spirit, one God, now and forever. Amen. ', 'First Sunday of Christmas', null, 2);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (8, 'Almighty God, whose blessed Son was circumcised for our sake in obedience to the Covenant of Abraham, and given the Name that is above every name: give us the grace to faithfully bear his Name, to worship him in the Spirit given in the New Covenant, and to proclaim him as the Savior of the world; who lives and reigns with you, in the unity of the Holy Spirit, one God, now and forever. Amen. ', 'The Holy Name of Our Lord Jesus Christ', null, 2);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (9, 'O God, who wonderfully created, and yet more wonderfully restored, the dignity of human nature: Grant that we may share the divine life of him who humbled himself to share our humanity, your Son Jesus Christ; who lives and reigns with you, in the unity of the Holy Spirit, one God, for ever and ever. Amen. ', 'The Second Sunday of Christmas', null, 2);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (10, 'O God, by the leading of a star you manifested your only Son to the peoples of the earth: Lead us, who know you now by faith, to your presence, where we may see your glory face to face; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen. ', 'The Epiphany, or the Manifestation of Christ to the Gentiles [January 6]
', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (11, 'Eternal Father, who at the baptism of Jesus revealed him to be your Son, anointing him with the Holy Spirit: grant to us, who are born again by water and the Spirit, that we may be faithful to our calling as your adopted children; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen.  ', 'The First Sunday of Epiphany [Baptism of Our Lord]', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (12, 'Almighty God, whose Son our Savior Jesus Christ is the light of the world: Grant that your people, illumined by your Word and Sacraments, may shine with the radiance of Christ’s glory, that he may be known, worshiped, and obeyed to the ends of the earth; through Jesus Christ our Lord; who with you and the Holy Spirit lives and reigns, one God, now and forever. Amen. ', 'The Second Sunday of Epiphany', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (13, 'Give us grace, O Lord, to answer readily the call of our Savior Jesus Christ and proclaim to all people the Good News of his salvation, that we and the whole world may perceive the glory of his marvelous works; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'The Third Sunday of Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (14, 'O God, you know that we are set in the midst of so many and grave dangers that in the frailty of our nature we cannot always stand upright: Grant us your strength and protection to support us in all dangers and carry us through every temptation; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, world without end. Amen.', 'The Fourth Sunday of Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (15, 'Almighty and everliving God, we humbly pray that, as your only-begotten Son was this day presented in the temple in the substance of our flesh, so we may be presented to you with pure and clean hearts by Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen. ', 'The Presentation of Christ in the Temple', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (16, 'O Lord, our Creator and Redeemer, we ask you to keep your household the Church continually in your true religion; so that we who trust in the hope of your heavenly grace may always be defended by your mighty power; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, both now and forever. Amen', 'The Fifth Sunday of Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (17, 'Almighty God, we ask you mercifully to look upon your people; that by your great goodness they may be governed and preserved evermore; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, now and forever. Amen.', 'The Sixth Sunday of Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (18, 'O God, the strength of all who put their trust in you: mercifully accept our prayers, and because through the weakness of our mortal nature we can do no good thing without you, grant us the help of your grace to keep your commandments; so that we may please you in will and deed; we ask this through Jesus Christ our Lord who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'The Seventh Sunday of Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (19, 'Lord God, you know that without your grace we cannot put our trust in anything that we do; defend us, by your mighty power, from all adversities which might assault and hurt our souls; we ask this through Jesus Christ our Lord; who with you and the Holy Spirit, lives and reigns as one God, now and forever. Amen. ', 'The Eighth Sunday of Epiphany', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (20, 'Give us grace, O Lord, to answer readily the call of our Savior Jesus Christ and proclaim to all people the Good News of his salvation, that we and the whole world may perceive the glory of his marvelous works; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'The Second to last Sunday of Epiphany [World Mission Sunday]', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (21, 'O God, who before the passion of your only-begotten Son revealed his glory upon the holy mountain: Grant that we, beholding by faith the light of his countenance, may be strengthened to bear our cross, and be changed into his likeness from glory to glory; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'The Last Sunday of Epiphany  [Transfiguration]', null, 3);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (22, 'Almighty and everlasting God, you hate nothing you have made and forgive the sins of all who are penitent: Create and make in us new and contrite hearts, that we, worthily lamenting our sins and acknowledging our wretchedness, may obtain of you, the God of all mercy, perfect remission and forgiveness; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'Ash Wednesday', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (23, 'Almighty God, whose blessed Son was led by the Spirit to be tempted by Satan: Come quickly to help us who are assaulted by many temptations; and, as you know the weaknesses of each of us, let each one find you mighty to save; through Jesus Christ your Son our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen. ', 'The First Sunday in Lent', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (24, 'Almighty God, you know that we have no power in ourselves to help ourselves: Keep us both outwardly in our bodies and inwardly in our souls, that we may be defended from all adversities which may happen to the body, and from all evil thoughts which may assault and hurt the soul; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen', 'The Second Sunday in Lent', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (25, 'Heavenly Father, you made us for yourself, and our hearts are restless until they rest in you: Look upon the heartfelt desires of your humble servants, and stretch forth the strong hand of your Majesty to be our defense against our enemies; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, world without end. Amen.', 'The Third Sunday in Lent
', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (26, 'Gracious Father, whose blessed Son Jesus Christ came down from heaven to be the true bread which gives life to the world: Evermore give us this bread, that he may live in us, and we in him; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen. ', 'The Fourth Sunday in Lent', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (27, 'Almighty God, you alone can bring into order the unruly wills and affections of sinners: Grant your people grace to love what you command and desire what you promise; that, among the swift and varied changes of this world, our hearts may surely there be fixed where true joys are to be found; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen. ', 'The Fifth Sunday in Lent [Passion Sunday]', null, 4);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (28, 'Almighty and everliving God, in your tender love for the human race you sent your Son our Savior Jesus Christ to take upon himself our nature, and to suffer death upon the cross, giving us the example of his great humility: Mercifully grant that we may walk in the way of his suffering, and also share in his resurrection; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Palm Sunday', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (29, 'Almighty God, whose most dear Son went not up to joy but first he suffered pain, and entered not into glory before he was crucified: Mercifully grant that we, walking in the way of the cross, may find it none other than the way of life and peace; through Jesus Christ your Son our Lord [who lives and reigns with you and the Holy Spirit, one God, for ever and ever]. Amen', 'Monday of Holy Week', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (30, 'Lord our God, whose blessed Son our Savior gave his back to be whipped and did not hide his face from shame and spitting: Give us grace to accept joyfully the sufferings of the present time, confident of the glory that shall be revealed; through Jesus Christ your Son our Lord [who lives and reigns with you and the Holy Spirit, one God, for ever and ever]. Amen.', 'Tuesday of Holy Week', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (31, 'Assist us mercifully with your grace, Lord God of our salvation; that we may enter with joy upon the meditation of those mighty acts by which you have promised us life and immortality; through Jesus Christ our Lord [who lives and reigns with you and the Holy Spirit, one God, for ever and ever]. Amen.', 'Wednesday of Holy Week', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (32, 'Almighty Father, whose dear Son, on the night before he suffered, instituted the Sacrament of his Body and Blood: Mercifully grant that we may receive it thankfully in remembrance of Jesus Christ our Lord, who in these holy mysteries gives us a pledge of eternal life; [and who lives and reigns with you and the Holy Spirit, one God, for ever and ever]. Amen. ', 'Maundy Thursday', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (33, 'Almighty God, we pray you graciously to behold this your family, for whom our Lord Jesus Christ was willing to be betrayed, and given into the hands of sinners, and to suffer death upon the cross; [who now lives and reigns with you and the Holy Spirit, one God, for ever and ever]. Amen.', 'Good Friday', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (34, 'O God, Creator of heaven and earth: Grant that, as the crucified body of your dear Son was laid in the tomb and rested on this holy Sabbath, so we may await with him the coming of the third day, and rise with him to newness of life; through Jesus Christ our Lord. Amen.
or
O God of the living, on this day your Son descended to the place of the dead: Look with kindness on all of us who wait in hope for liberation from the corruption of sin and death, and give us a share in the glory of the children of God, through Jesus Christ your Son, our Lord. Amen.

and

O God, who made this most holy night to shine with the glory of the Lord’s resurrection: Stir up that Spirit of adoption which is given to your Church in Baptism, that we, being renewed both in body and mind, may worship you in sincerity and truth; through Jesus Christ our Lord, who lives and reigns with you, in the unity of the Holy Spirit, one God, now and forever. Amen.

', 'Holy Saturday and Easter Eve ', null, 5);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (35, 'Almighty God, who through your only-begotten Son Jesus Christ overcame death and opened to us the gate of everlasting life: Grant that we, who celebrate with joy the day of the Lord’s resurrection, may be raised from the death of sin by your life-giving Spirit; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen

or

O God, who for our redemption gave your only begotten Son to die upon the cross, and by his glorious resurrection delivered us from the power of death and the devil: Grant us the grace to die daily to sin, that we may live with him in the joy of his resurrection, through the same, Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit now and forever. Amen', 'Easter Day', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (36, 'Grant, we pray, Almighty God, that we who celebrate with awe the Paschal feast may be found worthy to attain to everlasting joys; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen. ', 'Monday of Easter Week', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (37, 'O God, who by the glorious resurrection of your Son Jesus Christ destroyed death and brought life and immortality to light: Grant that we, who have been raised with him, may abide in his presence and rejoice in the hope of eternal glory; through Jesus Christ our Lord, to whom, with you and the Holy Spirit, be dominion and praise for ever and ever. Amen', 'Tuesday of Easter Week', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (38, 'O God, whose blessed Son made himself known to his disciples in the breaking of bread: Open the eyes of our faith, that we may behold him in all his redeeming work; who lives and reigns with you, in the unity of the Holy Spirit, one God, now and forever. Amen.', 'Wednesday of Easter Week', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (39, 'Almighty God, you show those in error the light of your truth so that they may return to the path of righteousness: Grant that all who have been reborn into the fellowship of Christ’s Body may show forth in their lives what they profess by their faith; through Jesus Christ our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen.', 'Thursday of Easter Week', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (40, 'Almighty Father, who gave your only Son to die for our sins and to rise for our justification: Give us grace so to put away the leaven of malice and wickedness, that we may always serve you in pureness of living and truth; through Jesus Christ your Son our Lord; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen', 'Friday of Easter Week', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (41, 'We thank you, heavenly Father, that you have delivered us from the dominion of sin and death and brought us into the kingdom of your Son; and we pray that, as by his death he has recalled us to life, so by his love he may raise us to eternal joys; who lives and reigns with you, in the unity of the Holy Spirit, one God, now and forever. Amen.', 'Saturday of Easter Week', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (42, 'Almighty and everlasting God, who in the Paschal mystery established the new covenant of reconciliation: Grant that all who have been reborn into the fellowship of Christ’s Body may show forth in their lives what they profess by their faith; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'The Second Sunday of Easter', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (43, 'Almighty God, you gave your only Son to be for us both a sacrifice for sin and an example of godly living: Give us the grace thankfully to receive this his inestimable benefit, and daily to follow the blessed steps of his most holy life; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, forever and ever. Amen.', 'The Third Sunday of Easter', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (44, 'The Fourth Sunday of Easter [Good Shepherd]', 'O God, whose Son Jesus is the good shepherd of your people: Grant that when we hear his voice we may know him who calls us each by name, and follow where he leads; who, with you and the Holy Spirit, lives and reigns, one God, for ever and ever. Amen.', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (45, 'Almighty God, whom truly to know is everlasting life: Grant us so perfectly to know your Son Jesus Christ to be the way, the truth, and the life, that we may steadfastly follow his steps in the way that leads to eternal life; through Jesus Christ your Son our Lord; who  lives and reigns with you, in the unity of the Holy Spirit, one God, for ever and ever. Amen', 'The Fifth Sunday of Easter', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (46, 'O God, you have prepared for those who love you such good things as surpass our understanding: Pour into our hearts such love towards you, that we, loving you in all things and above all things, may obtain your promises, which exceed all that we can desire; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'The Sixth Sunday of Easter [Rogation]', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (47, 'Grant, we pray, Almighty God, that as we believe your only-begotten Son our Lord Jesus Christ to have ascended into heaven, so we may also in heart and mind there ascend, and with him continually dwell; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Ascension Day', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (48, 'O God, the King of glory, you have exalted your only Son Jesus Christ with great triumph to your kingdom in heaven: Do not leave us comfortless, but send us your Holy Spirit to strengthen us, and exalt us to that place where our Savior Christ has gone before; who lives and reigns with you and the Holy Spirit, one God, in glory everlasting. Amen', 'The Sunday after the Ascension', null, 6);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (49, 'Almighty God, on this day you opened the way of eternal life to every race and nation by the promised gift of your Holy Spirit: Shed abroad this gift throughout the world by the preaching of the Gospel, that it may reach to the ends of the earth; through Jesus Christ our Lord; who  lives and reigns with you, in the unity of the Holy Spirit, one God, for ever and ever. Amen

or

O God, who on this day taught the hearts of your faithful people by sending to them the light of your Holy Spirit: Grant us by the same Spirit to have a right judgment in all things, and evermore to rejoice in his holy comfort; through Jesus Christ your Son our Lord; who  lives and reigns with you, in the unity of the Holy Spirit, one God, for ever and ever. Amen.', 'Day of Pentecost (Whitsunday)', null, 7);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (50, 'Almighty and everlasting God, you have given to us your servants grace, by the confession of a true faith, to acknowledge the glory of the eternal Trinity, and in the power of your divine Majesty to worship the Unity. Keep us steadfast in this faith and worship, and bring us at last to see you in your one and eternal glory, O Father; who with the Son and the Holy Spirit live and reign, one God, for ever and ever. Amen. ', 'Trinity Sunday', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (51, 'O God, the strength of all who put their trust in you: Mercifully accept our prayers, and because through the weakness of our mortal nature we can do no good thing without you, grant us the help of your grace to keep your commandments, that we may please you in will and deed; through Jesus Christ our Lord who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Sunday closest to May 11', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (52, 'O Lord, you never fail to support and govern those whom you bring up in your steadfast fear and love: Keep us, we pray, under your continual protection and providence, and give us a perpetual fear and love of your Name; through Jesus Christ our Lord who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'Sunday closest to May 18', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (53, 'O Lord, we ask you mercifully to hear us, and grant that we, to whom you have given the desire to pray, may by your mighty aid be defended and comforted in all our adversities; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Sunday closest to May 25', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (54, 'O God, the protector of all those who trust in you, without whom nothing is strong, nothing is holy: Increase and multiply in us your mercy, that, with you as our ruler and guide, we may so pass through things temporal that we lose not the things eternal; grant this, heavenly Father, for the sake of your Son, Jesus Christ; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Sunday closest to June 1', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (55, 'Grant, O Lord, that the course of this world may be so peaceably ordered in your providence, that your Church may joyfully serve you in all godly quietness and peace; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'Sunday closest to June 15', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (56, 'O Lord, from whom comes all good things;  grant us, your humble servants, the inspiration to always think and do those things which are good, that by your merciful guiding we may perform the same; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Sunday closest to June 22 ', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (57, 'Lord of all power and might, the author and giver of all good things: Graft in our hearts the love of your Name, increase in us true religion, nourish us with all goodness, and bring forth in us the fruit of good works; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Sunday closest to June 29
', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (58, 'O God, your never-failing providence sets in order all things both in heaven and on earth: Put away from us all hurtful things, and give us those things which are profitable for us; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Sunday closest to July 6
', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (59, 'Grant us, Lord, we pray, the spirit to think and do always those things that are right, that we, who cannot exist without you, may by you be enabled to live according to your will; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Sunday closest to July 13', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (60, 'Hear us, O Lord, when we cry out to you; and that we might receive what we ask, enable us by your Holy Spirit to ask only what accords with your will; through Jesus Christ our Lord; who  with you and the same Spirit lives and reigns for ever and ever. Amen.', 'Sunday closest to July 20', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (61, 'O God, you declare your almighty power chiefly in showing mercy and pity: Grant us the fullness of your grace, that we, running to obtain your promises, may become partakers of your heavenly treasure; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen', 'Sunday closest to July 27 ', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (62, 'Almighty and everlasting God, you are always more ready to hear than we to pray, and to give more than we either desire or deserve: Pour upon us the abundance of your mercy, forgiving us those things of which our conscience is afraid, and giving us those good things for which we are not worthy to ask, except through the merits and mediation of Jesus Christ our Savior; who lives and reigns with you and the Holy Spirit, one God, for ever and ever.', 'Sunday closest to August 3', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (63, 'Almighty and merciful God, it is only by your grace that your faithful people offer you true and laudable service: Grant that we may run without stumbling to obtain your heavenly promises; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, now and forever. Amen.', 'Sunday closest to August 10', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (64, 'Almighty God, give us the increase of faith, hope, and love; and, so that we may obtain what you have promised, make us love what you command; through Jesus Christ our Lord who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Sunday closest to August 17
', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (65, 'Keep your Church in safety, O Lord; for without your grace the frailty of our nature cannot but make us fall; so in your mercy keep us from all things hurtful, and lead us in all things profitable for our salvation; through Jesus Christ our Lord who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'Sunday Closest to August 24', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (66, 'Let your continual mercy, O Lord, cleanse and defend your Church; and, because it cannot continue in safety without your help, protect and govern it always by your goodness; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'Sunday closest to August 31', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (67, 'O Lord, we pray that your grace may always both precede and follow after us, that we may continually be given to good works; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, now and forever. Amen.
', 'Sunday closest to September 7', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (68, 'Lord God, grant your people grace to withstand the temptations of the world, the flesh, and the devil; that we may love you faithfully with all our heart and soul and mind and strength; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, now and forever. Amen.', 'Sunday closest to September 14', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (69, 'Almighty and merciful God, in your goodness keep us, we pray, from all things that may hurt us, that we, being ready both in mind and body, may accomplish with free hearts those things which belong to your purpose; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, now and forever. Amen.', 'Sunday closest to September 21 ', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (70, 'Merciful Lord, grant to your faithful people pardon and peace; that by your grace we may be cleansed from all our sins and serve you with a quiet mind; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, now and forever. Amen.', 'Sunday closest to September 28 ', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (71, 'Keep, O Lord, your household the Church in continual godliness; that through your protection it may be free from all adversities, and devotedly serve you in good works, to the glory of your Name; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, now and forever. Amen.', 'Sunday closest to October 5 ', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (72, 'God, our refuge and strength, true source of all godliness: Graciously hear the devout prayers of your Church, and grant that those things which we ask faithfully we may obtain effectually; through Jesus Christ our Lord; who  sits at your right hand to intercede for us, and who with you and the Holy Spirit lives and reigns in everlasting glory. Amen.', 'Sunday closest to October 12 ', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (73, 'Set us free, loving Father, from the bondage of our sins, and in your goodness and mercy give us the liberty of that abundant life which you have made known to us in our Savior Jesus Christ; who lives and reigns with you, in the unity of the Holy Spirit, one God, now and forever. Amen.', 'Sunday closest to October 19', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (74, 'Almighty and everlasting God, you govern all things both in heaven and on earth: Mercifully hear the supplications of your people, and in our time grant us your peace; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Sunday closest to October 26 ', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (75, 'Almighty God, you have knit together your elect in one communion and fellowship in the mystical body of your Son Christ our Lord: Give us grace so to follow your blessed saints in all virtuous and godly living, that we may come to those ineffable joys that you have prepared for those who truly love you; through Jesus Christ our Lord; who  with you and the Holy Spirit lives and reigns, one God, in glory everlasting. Amen.', 'All Saint''s Day', null, 10);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (76, 'Grant us, Lord, not to be anxious about earthly things, but to love things heavenly; and even now, while we are placed among things that are passing away, to hold fast to those that shall endure; through Jesus Christ our Lord; who  lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.', 'Sunday closest to November 2 ', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (77, 'O God, whose blessed Son came into the world that he might destroy the works of the devil and make us children of God and heirs of eternal life: Grant that, having this hope, we may purify ourselves as he is pure; that, when he comes again with power and great glory, we may be made like him in his eternal and glorious kingdom; where he lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen. ', 'Sunday closest to November 9', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (78, ' Stir up, O Lord, the wills of your faithful people; that they may plenteously bring forth the fruit of good works, as they await the coming of our Lord Jesus Christ to restore all things to their original perfection; who with you and the Holy Spirit lives and reigns for ever and ever. Amen ', 'Sunday closest to November 16', null, 8);
INSERT INTO lectionary_db.propers (id, collect, name, fixed_feast_id, season_id) VALUES (79, 'Almighty and everlasting God, whose will it is to restore all things in your well-beloved Son, the King of kings and Lord of lords: Mercifully grant that the peoples of the earth, divided and enslaved by sin, may be freed and brought together under his most gracious rule; who lives and reigns with you and the Holy Spirit, one God, now and forever. Amen. ', 'Sunday closest to November 23 [Christ the King]', null, 8);